apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: model-test-2
  namespace: seldon
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://mirgor_model/mnt/models/model.pkl
      name: classifier
    name: default
    replicas: 1
